#ifndef TAKE_DERIVATIVE_H
#define TAKE_DERIVATIVE_H

enum take_derivative_return_e
{   
    TAKE_DERIVATIVE_RETURN_SUCCESS,
    TAKE_DERIVATIVE_UNDEFINED_FUNCTION,
    TAKE_DERIVATIVE_TREE_ERROR,
    TAKE_DERIVATIVE_INCORRECT_EXPRESSION
};

#endif //TAKE_DERIVATIVE_H