#ifndef TAKE_DERIVATIVE_H
#define TAKE_DERIVATIVE_H

enum take_derivative_return_e
{   
    TAKE_DERETATIVE_RETURN_SUCCESS,
    TAKE_DERETATIVE_UNDEFINED_FUNCTION,
    TAKE_DERETATIVE_TREE_ERROR
};

#endif //TAKE_DERIVATIVE_H